use_frameworks!

platform :ios, '9.0'

target 'BRPTInteractiveView_Example' do
  pod 'BRPTInteractiveView', :path => '../'

  target 'BRPTInteractiveView_Tests' do
    inherit! :search_paths

    
  end
end
